/* Network */
export const REQUEST = '[REQUEST]';
export const PENDING = 'API_PENDING';
export const SUCCESS = 'API_SUCCESS';
export const FAILURE = 'API_FAILURE';

/* API */
export const API_REQUEST = 'API_REQUEST';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILURE = 'API_FAILURE';
export const API_PENDING = 'API_PENDING';

/* CRUD */
export const CREATE = 'CREATE';
export const READ = 'READ';
export const READ_SINGLE = 'READ_SINGLE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const MASSIVE = 'MASSIVE';
export const DOWNLOAD = 'DOWNLOAD';
export const SET = 'SET';
export const CLEAN = 'CLEAN';
export const ADD = 'ADD';

/* Count */
export const COUNTER = 'COUNTER';

/* App */
export const SET_RIGHT_DRAWER_VISIBILITY = 'SET_RIGHT_DRAWER_VISIBILITY';
export const CHANGE_MESSAGE_DEBTOR = 'CHANGE_MESSAGE_DEBTOR';
export const SET_USER_SERVICE = 'SET_USER_SERVICE';
export const SET_COMPANY_DATA = 'SET_COMPANY_DATA';
export const CLEAN_USER_SERVICE = 'CLEAN_USER_SERVICE';
export const DATE = 'DATE';
export const TIME = '[TIME]';
export const ROLES = 'ROLES';

/* Couriers */
export const COURIERS = '[COURIERS]';
export const CLIENT = 'CLIENT';
export const REQUEST_COURIERS_BRANCH_OFFICE = `${COURIERS} BRANCH_OFFICE`;
export const COURIER_SET_COURIERS_BRANCH_OFFICE = `${COURIERS} COURIER_SET_COURIERS_BRANCH_OFFICE`;
export const REQUEST_COURIERS_BRANCH_OFFICE_PENDING = `${COURIERS} BRANCH_OFFICE ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_BRANCH_OFFICE_SUCCESS = `${COURIERS} BRANCH_OFFICE ${REQUEST} ${READ}_${SUCCESS}`;
export const CLEAN_COURIERS_BRANCH_OFFICES_STATE = 'CLEAN_COURIERS_BRANCH_OFFICES_STATE';
export const SET_COURIER_DEFAULT_ALGORITHM = 'SET_COURIER_DEFAULT_ALGORITHM';
export const SET_COURIER_DEFAULT_DAYS = 'SET_COURIER_DEFAULT_DAYS';
export const SET_SELECTED_COURIER = 'SET_SELECTED_COURIER';
export const SET_COURIER_RIGHT_DRAWER_VISIBILITY = 'SET_COURIER_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIER = 'CLEAN_SELECTED_COURIER';
export const CLEAN_COURIER_STATE = 'CLEAN_COURIER_STATE';
export const ALGORITHM = 'ALGORITHM';
export const BRANCH_OFFICE = 'BRANCH_OFFICE';
export const SET_SELECT_CONFIG = `${COURIERS} SET_SELECT_CONFIG`;
export const SERVICES_CONFIG = 'SERVICES_CONFIG';
export const SET_BACKOFFICE_COURIERS_ENABLED = 'SET_BACKOFFICE_COURIERS_ENABLED';
export const SET_PRICES_V3_ENABLED = 'SET_PRICES_V3_ENABLED';
export const SET_MULTIORIGIN_ENABLED = 'SET_MULTIORIGIN_ENABLED';
export const PRICESV3COURIER = 'PRICESV3COURIER';
export const MULTIORIGIN = 'MULTIORIGIN';
export const BACKOFFICECOURIER = 'BACKOFFICECOURIER';
export const ENABLED = 'ENABLED';
export const SDD = 'SDD';

/* Generic Couriers */
export const GENERIC_COURIERS = '[GENERIC_COURIERS]';
export const REQUEST_GENERIC_COURIERS_PENDING = `${GENERIC_COURIERS} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_GENERIC_COURIERS_SUCCESS = `${GENERIC_COURIERS} ${REQUEST} ${READ}_${SUCCESS}`;

/* Account */
export const USER = '[USER]';
export const PLANS = '[PLANS]';
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const RECOVER_PASSWORD_CODE = 'RECOVER_PASSWORD_CODE';
export const RESET_PASSWORD_USER = 'RESET_PASSWORD_USER';
export const SAVE_CODE_IN_STORE = 'SAVE_CODE_IN_STORE';
export const SAVE_USER_IN_STORE = `${USER} SAVE_USER_IN_STORE`;
export const CODE_IS_VERIFIED = 'CODE_IS_VERIFIED';
export const RESET_PASSWORD_ACCOUNT = 'RESET_PASSWORD_ACCOUNT';

/* Orders */
export const ORDERS = 'ORDERS';
export const ORDER = 'ORDER';
export const SYNC = 'SYNC';
export const CREATE_ORDERS_PENDING = `${ORDERS} ${REQUEST} ${CREATE}_${PENDING}`;
export const CREATE_ORDERS_SUCCESS = `${ORDERS} ${REQUEST} ${CREATE}_${SUCCESS}`;
export const REQUEST_ORDER_PENDING = `${ORDERS} ${REQUEST} ${READ_SINGLE}_${PENDING}`;
export const REQUEST_ORDER_SUCCESS = `${ORDERS} ${REQUEST} ${READ_SINGLE}_${SUCCESS}`;
export const UPDATE_ORDERS_PENDING = `${ORDERS} ${REQUEST} ${UPDATE}_${PENDING}`;
export const UPDATE_ORDERS_SUCCESS = `${ORDERS} ${REQUEST} ${UPDATE}_${SUCCESS}`;
export const DELETE_ORDERS_PENDING = `${ORDERS} ${REQUEST} ${DELETE}_${PENDING}`;
export const DELETE_ORDERS_SUCCESS = `${ORDERS} ${REQUEST} ${DELETE}_${SUCCESS}`;
export const DELETE_MASSIVE_ORDERS_PENDING = `${ORDERS} ${REQUEST} MASSIVE_${DELETE}_${PENDING}`;
export const DELETE_MASSIVE_ORDERS_SUCCESS = `${ORDERS} ${REQUEST} MASSIVE_${DELETE}_${SUCCESS}`;
export const DOWNLOAD_ORDERS_PENDING = `${ORDERS} ${REQUEST} DOWNLOAD_${PENDING}`;
export const DOWNLOAD_ORDERS_SUCCESS = `${ORDERS} ${REQUEST} DOWNLOAD_${SUCCESS}`;
export const FILTER_ORDERS_PENDING = `${ORDERS} ${REQUEST} FILTER_${PENDING}`;
export const FILTER_ORDERS_SUCCESS = `${ORDERS} ${REQUEST} FILTER_${SUCCESS}`;
export const UPDATE_ORDER_IN_STORE = 'UPDATE_ORDER_IN_STORE';
export const SET_ORDERS_BOTTOM_DRAWER_VISIBILITY = 'SET_ORDERS_BOTTOM_DRAWER_VISIBILITY';
export const CLEAN_ORDER = 'CLEAN_ORDER';
export const SHOW_SELECTED_ORDERS = 'SHOW_SELECTED_ORDERS';
export const CLEAN_SELECTED_ORDERS = 'CLEAN_SELECTED_ORDERS';
export const MASIVE_ORDER_EDITION_MODAL = 'MASIVE_ORDER_EDITION_MODAL';

/* Orders - form */
export const SAVE_ORDER_IN_STORE = 'SAVE_ORDER_IN_STORE';
export const SAVE_FORM_ORDER_IN_STORE = 'SAVE_FORM_ORDER_IN_STORE';
export const GET_NEW_ORDER_FORM_VALUES = 'GET_NEW_ORDER_FORM_VALUES';
export const CLEAN_ORDER_FROM_STORE = 'CLEAN_ORDER_FROM_STORE';
export const SET_MASIVE_ORDERS_MODAL_VISIBILTY = 'SET_MASIVE_ORDERS_MODAL_VISIBILTY';
export const ORDERS_COUNTER_SUCCESS = `${ORDERS} ${COUNTER} ${API_SUCCESS}`;

/* Orders - xls */
export const XLS = 'XLS';
export const CLEAN_XLS_DATA = 'CLEAN_XLS_DATA';
export const ADD_SKUS_TO_XLSX = 'ADD_SKUS_TO_XLSX';
export const REMOVE_SKUS_TO_XLSX = 'REMOVE_SKUS_TO_XLSX';
export const IMPORTING_FILE = 'IMPORTING_FILE';

/* Shipments */
export const SET_PDF_MODAL_VISIBILITY = 'SET_PDF_MODAL_VISIBILITY';
export const ASYNC_DOWNLOAD = `ASYNC_DOWNLOAD`;
export const VALIDATE_REFERENCE = `VALIDATE_REFERENCE`;

/* SignUp */
export const SIGN_UP = '[SIGN_UP]';
export const COMMERCIAL = '[COMMERCIAL]';

/* Modal */
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

/* Packages */
export const PACKING = 'PACKING';
export const SET_SELECTED_PACKING = 'SET_SELECTED_PACKING';
export const CLEAR_PACKING = 'CLEAR_PACKING';

/* Products */
const PRODUCTS = '[PRODCUTS]';
export const REQUEST_PRODUCTS_PENDING = `${PRODUCTS} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_PRODUCTS_SUCCESS = `${PRODUCTS} ${REQUEST} ${READ}_${SUCCESS}`;
export const REQUEST_PRODUCT_PENDING = `${PRODUCTS} ${REQUEST} ${READ_SINGLE}_${PENDING}`;
export const REQUEST_PRODUCT_SUCCESS = `${PRODUCTS} ${REQUEST} ${READ_SINGLE}_${SUCCESS}`;
export const CREATE_PRODUCT_PENDING = `${PRODUCTS} ${REQUEST} ${CREATE}_${PENDING}`;
export const CREATE_PRODUCT_SUCCESS = `${PRODUCTS} ${REQUEST} ${CREATE}_${SUCCESS}`;
export const UPDATE_PRODUCT_PENDING = `${PRODUCTS} ${REQUEST} ${UPDATE}_${PENDING}`;
export const UPDATE_PRODUCT_SUCCESS = `${PRODUCTS} ${REQUEST} ${UPDATE}_${SUCCESS}`;
export const DELETE_PRODUCT_PENDING = `${PRODUCTS} ${REQUEST} ${DELETE}_${PENDING}`;
export const DELETE_PRODUCT_SUCCESS = `${PRODUCTS} ${REQUEST} ${DELETE}_${SUCCESS}`;
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

/* Address */
export const ADDRESSES = '[ADDRESSES]';
export const REQUEST_ADDRESSES_PENDING = `${ADDRESSES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_ADDRESSES_SUCCESS = `${ADDRESSES} ${REQUEST} ${READ}_${SUCCESS}`;
export const REQUEST_ADDRESS_BY_TYPE_PENDING = `${ADDRESSES} ${REQUEST} ${READ}_BY_TYPE_${PENDING}`;
export const REQUEST_ADDRESS_BY_TYPE_SUCCESS = `${ADDRESSES} ${REQUEST} ${READ}_BY_TYPE_${SUCCESS}`;
export const REQUEST_ADDRESS_BY = `${ADDRESSES} REQUEST_ADDRESS_BY`;
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS';
export const CLEAR_ADDRESSES_BY_TYPE = 'CLEAR_ADDRESSES_BY_TYPE';

/* Countries */
export const COUNTRIES = '[COUNTRIES]';

/* Companies */
export const COMPANIES = '[COMPANIES]';
export const SET_COMPANIES_PAGINATION = 'SET_COMPANIES_PAGINATION';
export const SET_SELECTED_COMPANY = 'SET_SELECTED_COMPANY';
export const CLEAN_SELECTED_COMPANY = 'CLEAN_SELECTED_COMPANY';
export const SET_COMPANIES_FILTERS = 'SET_COMPANIES_FILTERS';

/* Filters */
export const STORE_FILTERS = 'STORE_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';

/* Email Notification */
export const EMAIL_NOTIFICATION = '[EMAIL_NOTIFICATION]';
export const EMAIL_NOTIFICATION_TEMPLATE = '[EMAIL_NOTIFICATION_TEMPLATE]';
export const SET_EMAIL_PROPS = 'SET_EMAIL_PROPS';
export const SET_VISIBLE_POPOVER = 'SET_VISIBLE_POPOVER';
export const SET_EMAIL_TAB = `${EMAIL_NOTIFICATION} SET_EMAIL_TAB`;
export const CLEAR_EMAIL_TAB = `${EMAIL_NOTIFICATION} CLEAR_EMAIL_TAB`;
export const FORMAT_BASE = 'FORMAT_BASE';
export const SWITCH = 'SWITCH';
export const STATE = 'STATE';
export const SET_LOGO = 'SET_LOGO';
export const SET_BACKGROUND_HEADER = 'SET_BACKGROUND_HEADER';
export const SET_BACKGROUND_FOOTER = 'SET_BACKGROUND_FOOTER';
export const SET_FONT_COLOR_FOOTER = 'SET_FONT_COLOR_FOOTER';
export const SEND_TEST_EMAIL_NOTIFICATION = 'SEND_TEST_EMAIL_NOTIFICATION';

/* Pickups */
export const STORE_PICKUP = 'STORE_PICKUP';

/* Pick and Pack */
export const PICK_AND_PACK = '[PICK_AND_PACK]';
export const SAVE_PICK_AND_PACK_IN_STORE = 'SAVE_PICK_AND_PACK_IN_STORE';
export const SET_PICK_AND_PACK_PAGINATION = 'SET_PICK_AND_PACK_PAGINATION';
export const SET_PICK_AND_PACK_FILTERS = 'SET_PICK_AND_PACK_FILTERS';
export const SET_PICK_AND_PACK_ID = 'SET_PICK_AND_PACK_ID';
export const SET_STATE = 'SET_STATE';
export const SET_PICK_AND_PACK_FORM = 'SET_PICK_AND_PACK_FORM';

/* Admission Types */
export const ADMISSION_TYPES = 'ADMISSION_TYPES';
export const COURIER_ADMISSION_TYPES = 'COURIER_ADMISSION_TYPES';
export const ADMISSION_TYPES_COVERAGES = 'ADMISSION_TYPES_COVERAGES';

/* Dashboard */
export const DASHBOARD = '[DASHBOARD]';
export const CHART = '[CHART]';
export const SET_ANALYTICS_FILTER = 'SET_ANALYTICS_FILTER';
export const SET_ACTIVE_METRIC = 'SET_ACTIVE_METRIC';
export const CLEAN_ANALYTICS_STATE = 'CLEAN_ANALYTICS_STATE';

/* My Suite */
export const MY_SUITE = '[MY_SUITE]';
export const MY_SUITE_CHART = '[MY_SUITE_CHART]';
export const OPERATIONAL_PICKUP = '[OPERATIONAL_PICKUP]';
export const SET_OPERATIONAL_ANALYTICS_FILTER = 'SET_OPERATIONAL_ANALYTICS_FILTER';
export const CLEAN_OPERATIONAL_ANALYTICS_FILTER = 'CLEAN_OPERATIONAL_ANALYTICS_FILTER';
export const SEND_IDS_TO_SHIPMENTS = 'SEND_IDS_TO_SHIPMENTS';
export const PAYMENTS = '[PAYMENTS]';
export const SET_PAYMEMT_CURENT_PAGE = 'SET_PAYMEMT_CURENT_PAGE';
export const CLEAN_PAYMENT_DETAILS = 'CLEAN_PAYMENT_DETAILS';
export const SET_LOADING = 'SET_LOADING';
export const DOWNLOAD_PAYMENTS_PENDING = 'DOWNLOAD_PAYMENTS_PENDING';
export const DOWNLOAD_PAYMENTS_SUCCESS = 'DOWNLOAD_PAYMENTS_SUCCESS';
export const DOWNLOAD_PAYMENTS_SHIPMENTS_PENDING = 'DOWNLOAD_PAYMENTS_SHIPMENTS_PENDING';
export const DOWNLOAD_PAYMENTS_SHIPMENTS_SUCCESS = 'DOWNLOAD_PAYMENTS_SHIPMENTS_SUCCESS';
export const SET_PAYMEMT_CURENT_YEAR = 'SET_PAYMEMT_CURENT_YEAR';
export const SET_PAYMENT_SELECTED_YEAR = 'SET_PAYMENT_SELECTED_YEAR';
export const SET_PAYMEMT_CURENT_MONTH = 'SET_PAYMEMT_CURENT_MONTH';
export const CHANGE_PAYMEMT_POPOVER_VISIBILITY = 'CHANGE_PAYMEMT_POPOVER_VISIBILITY';
export const SET_PAYMEMT_RIGHT_DRAWER_VISIBILITY = `${PAYMENTS} SET_PAYMEMT_RIGHT_DRAWER_VISIBILITY`;
export const SET_PAYMEMT_SHIPMENTS_PAGINATION = `${PAYMENTS} SET_PAYMEMT_SHIPMENTS_PAGINATION`;
export const CLEAR_PAYMEMT_RIGHT_DRAWER_VISIBILITY = `${PAYMENTS} CLEAR_PAYMEMT_RIGHT_DRAWER_VISIBILITY`;
export const CHANGE_PAYMEMT_TAB = `${PAYMENTS} CHANGE_PAYMEMT_TAB`;
export const REQUEST_DETAILS_PAYMENT = `${PAYMENTS} REQUEST_DETAILS_PAYMENT`;

/* Labels */
export const LABELS = '[LABELS]';

/* Fulfillment */
export const FULFILLMENT = '[FULFILLMENT]';
export const MOVEMENTS = '[MOVEMENTS]';
export const ADD_SELECTED_SKU = 'ADD_SELECTED_SKU';
export const DELETE_SELECTED_SKU = 'DELETE_SELECTED_SKU';
export const ADD_PRODUCTS_TO_ORDERS = 'ADD_PRODUCTS_TO_ORDERS';
export const ADD_SIZE_TO_SHIPMENT = 'ADD_SIZE_TO_SHIPMENT';
export const BOXIFY = 'BOXIFY';
export const INVENTORY = '[INVENTORY]';
export const SKUS = '[SKUS]';
export const WAREHOUSE = '[WAREHOUSE]';
export const SET_INVENTORY_RIGHT_DRAWER_VISIBILITY = 'SET_INVENTORY_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_INVENTORY = 'CLEAN_SELECTED_INVENTORY';
export const CLEAN_SELECTED_SKU = 'CLEAN_SELECTED_SKU';
export const CLEAN_SKUS_SELECTED = 'CLEAN_SKUS_SELECTED';
export const SET_FULFILLMENT_PAGINATION = 'SET_FULFILLMENT_PAGINATION';
export const CLEAN_FULFILLMENT_FILTERS = 'CLEAN_FULFILLMENT_FILTERS';
export const SET_INVENTORIES_FILTERS = 'SET_INVENTORIES_FILTERS';
export const MODIFY_SKULIST_MIN = 'MODIFY_SKULIST_MIN';
export const REQUEST_WAREHOUSES = `${FULFILLMENT} ${WAREHOUSE}`;

/* Prices */
export const QUOTATIONS = '[QUOTATIONS]';
export const REQUEST_QUOTATIONS = 'REQUEST_QUOTATION';
export const SET_QUOTATIONS = 'SET_QUOTATIONS';
export const RESET_QUOTATIONS = 'RESET_QUOTATION';
export const SET_ATTRIBUTE_QUOTATIONS = 'SET_ATTRIBUTE_QUOTATIONS';

/* Returns */
export const RETURNS = '[RETURNS]';
export const SET_RETURNS_FILTERS = 'SET_RETURNS_FILTERS';
export const SET_RETURNS_PAGINATION_FILTERS = 'SET_RETURNS_PAGINATION_FILTERS';
export const SET_SELECTED_ROWS = 'SET_SELECTED_ROWS';
export const RETURNS_COUNTER = `${RETURNS} ${COUNTER}`;

/* Calendar */
export const MONITOR = '[MONITOR]';
export const MONITOR_REQUEST = `${MONITOR} REQUEST_MONITOR`;
export const REQUEST_MONITOR_PENDING = `${MONITOR} REQUEST_MONITOR_PENDING`;
export const MONITOR_SET_ATTRIBUTES = `${MONITOR} MONITOR_SET_ATTRIBUTES`;
export const SET_RIGHT_DRAWER_MONITOR_STATUS = `${MONITOR} SET_RIGHT_DRAWER_MONITOR_STATUS`;
export const CLEAR_RIGHT_DRAWER_MONITOR_STATUS = `${MONITOR} CLEAR_RIGHT_DRAWER_MONITOR_STATUS`;
export const MONITOR_CLEAR_CALENDAR = `${MONITOR} CLEAR_CALENDAR`;
export const CHANGE_SELECTED_STATUS = `${MONITOR} CHANGE_SELECTED_STATUS`;

/* Pickups */
export const PICKUP = '[PICKUP]';
export const CLEAN_PICKUP_FROM_STORE = 'CLEAN_PICKUP_FROM_STORE';
export const SET_PICKUP_PDF_MODAL_VISIBILITY = 'SET_PICKUP_PDF_MODAL_VISIBILITY';
export const SET_PICKUP_MANIFEST_MODAL_VISIBILITY = 'SET_PICKUP_MANIFEST_MODAL_VISIBILITY';

/* TICKETS */
export const TICKETS = '[TICKETS]';
export const SET_TICKETS_RIGHT_DRAWER_VISIBILITY = 'SET_TICKETS_RIGHT_DRAWER_VISIBILITY';
export const SET_SELECTED_TICKET = 'SET_SELECTED_TICKET';
export const CLEAN_SELECTED_TICKET = 'CLEAN_SELECTED_TICKET';

/* WHATSAPP NOTIFICATIONS */
export const WHATSAPP_NOTIFICATION = '[WHATSAPP_NOTIFICATION]';
export const WHATSAPP_STATE = '[WHATSAPP_STATE]';
export const SET_WHATSAPP_PROPS = 'SET_WHATSAPP_PROPS';
export const SET_WHATSAPP_TAB = `${WHATSAPP_NOTIFICATION} SET_WHATSAPP_TAB`;
export const CLEAR_WHATSAPP_TAB = `${WHATSAPP_NOTIFICATION} CLEAR_WHATSAPP_TAB`;

/* PRINTER LABELS */
export const PRINTERS = '[PRINTERS]';
export const PRINTER_LABELS = `${PRINTERS} PRINTER_LABELS`;
export const REMOVE_SHIPMENTS_TO_PRINT = `${PRINTERS} REMOVE_SHIPMENTS_TO_PRINT`;
export const SHIPMENTS_TO_PRINT = `${PRINTERS} SHIPMENTS_TO_PRINT`;
export const SEARCH_SHIPMENTS_BY_REFERENCES = `${PRINTERS} SEARCH_SHIPMENTS_BY_REFERENCES`;
export const CLEAR_SHIPMENTS_TO_PRINT = `${PRINTERS} CLEAR_SHIPMENTS_TO_PRINT`;
export const SET_PRINTER_SELECTED_SHIPMENTS_ROWS = `${PRINTERS} SET_PRINTER_SELECTED_SHIPMENTS_ROWS`;
export const SET_PRINTER_SHIPMENTS_BOTTOM_DRAWER_VISIBILITY = `${PRINTERS} SET_PRINTER_SHIPMENTS_BOTTOM_DRAWER_VISIBILITY`;
export const SET_PRINTER_SHIPMENTS_MODAL_VISIBILITY = `${PRINTERS} SET_PRINTER_SHIPMENTS_MODAL_VISIBILITY`;
export const SET_PRINTER_MODAL_UPLOAD_ORDER_VISIBILITY = `${PRINTERS} SET_PRINTER_MODAL_UPLOAD_ORDER_VISIBILITY`;
export const SET_PRINTER_FILTER = `${PRINTERS} SET_PRINTER_FILTER`;

// SALESMAN
export const SALESMAN = '[SALESMAN]';
export const REQUEST_SALESMAN = 'REQUEST_SALESMAN';

// PAGINATION
export const RESET_PAGINATION = 'RESET_PAGINATION';

// SEARCH
export const SEARCH = '[SEARCH]';
export const REQUEST_SHIPMENTS_QUERY = 'REQUEST_SHIPMENTS_QUERY';
export const REQUEST_ORDERS_QUERY = 'REQUEST_ORDERS_QUERY';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY';
export const SET_SEARCH_SHIPMENTS_BOTTOM_DRAWER_VISIBILITY =
  'SET_SEARCH_SHIPMENTS_BOTTOM_DRAWER_VISIBILITY';
export const SET_SEARCH_ORDERS_BOTTOM_DRAWER_VISIBILITY =
  'SET_SEARCH_ORDERS_BOTTOM_DRAWER_VISIBILITY';
export const SET_SEARCH_ORDERS_RIGHT_DRAWER_VISIBILITY =
  'SET_SEARCH_ORDERS_RIGHT_DRAWER_VISIBILITY';
export const SET_SEARCH_SHIPMENTS_RIGHT_DRAWER_VISIBILITY =
  'SET_SEARCH_SHIPMENTS_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SEARCH_SELECTED_SHIPMENTS = 'CLEAN_SEARCH_SELECTED_SHIPMENTS';
export const CLEAN_SEARCH_SELECTED_ORDERS = 'CLEAN_SEARCH_SELECTED_ORDERS';
export const SET_SEARCH_SELECTED_SHIPMENTS = 'SET_SEARCH_SELECTED_SHIPMENTS';
export const SET_SEARCH_SELECTED_ORDERS = 'SET_SEARCH_SELECTED_ORDERS';
export const FIND_SHIPMENT = 'FIND_SHIPMENT';
export const FIND_ORDER = 'FIND_ORDER';
export const CLEAR_SEARCH_ORDERS_RIGHT_DRAWER_VISIBILITY =
  'CLEAR_SEARCH_ORDERS_RIGHT_DRAWER_VISIBILITY';
export const CLEAR_SEARCH_SHIPMENTS_RIGHT_DRAWER_VISIBILITY =
  'CLEAR_SEARCH_SHIPMENTS_RIGHT_DRAWER_VISIBILITY';

// MAPS
export const SET_ADDRESS = 'SET_ADDRESS';

/* EVENTS */
export const SET_DOWNLOADS_RIGHT_DRAWER = 'SET_DOWNLOADS_RIGHT_DRAWER';
export const DOWNLOADS = 'DOWNLOADS';
export const SET_DOWNLOAD = 'SET_DOWNLOAD';
export const REMOVE_FROM_STORE = 'REMOVE_FROM_STORE';
export const NOTIFICATIONS = 'NOTIFICATIONS';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_DOWNLOAD_READED = 'SET_DOWNLOAD_READED';
export const UPDATE_DEBTOR_STATUS = 'UPDATE_DEBTOR_STATUS';

/* Automatizations */
export const AUTOMATIZATIONS = '[AUTOMATIZATIONS]';
export const SET_AUTOMATIZATIONS = 'SET_AUTOMATIZATIONS';

/* PARTNER */
export const PARTNER = '[PARTNER]';
export const REQUEST_PARTNER = `${PARTNER} REQUEST_PARTNER`;
export const CLEAR_PARTNER = `${PARTNER} CLEAR_PARTNER`;

/* DROP OUT */
export const DEACTIVATE = '[DEACTIVATE]';
export const REACTIVATE = '[REACTIVATE]';

/* API Configuration */
export const API = '[API]';

/* Administrative */
export const ADMINISTRATIVE = '[ADMINISTRATIVE]';

/* Company Segments */
export const COMPANY_SEGMENTS = '[COMPANY_SEGMENTS]';

/* Operative */
export const OPERATIVE = '[OPERATIVE]';
export const ACCOUNT = '[ACCOUNT]';
export const ADD_EMAIL_TO_LIST = 'ADD_EMAIL_TO_LIST';
export const DELETE_EMAIL_FROM_LIST = 'DELETE_EMAIL_FROM_LIST';
export const CONTACTS = 'CONTACTS';
export const HEROS = 'HEROS';
export const ORIGINS = 'ORIGINS';
export const SAVE_FORM_CONTACT_IN_STORE = 'SAVE_FORM_CONTACT_IN_STORE';
export const SET_INACTIVE_ACCOUNT = 'SET_INACTIVE_ACCOUNT';
export const AUTOMATIC_UPDATE = 'AUTOMATIC_UPDATE';
export const AREA = 'AREA';
export const SET_SELECTED_AREA_ID = 'SET_SELECTED_AREA_ID';
export const SET_IS_RIGHT = `${AREA} SET_IS_RIGHT`;

/* Delivery Types */
export const DELIVERY_TYPES = '[DELIVERY_TYPES]';
export const REQUEST_DELIVERY_TYPES_PENDING = `${DELIVERY_TYPES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_DELIVERY_TYPES_SUCCESS = `${DELIVERY_TYPES} ${REQUEST} ${READ}_${SUCCESS}`;

/* Couriers Delivery Types */
export const COURIERS_DELIVERY_TYPES = '[COURIERS_DELIVERY_TYPES]';
export const REQUEST_COURIERS_DELIVERY_TYPES_PENDING = `${COURIERS_DELIVERY_TYPES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_DELIVERY_TYPES_SUCCESS = `${COURIERS_DELIVERY_TYPES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIERS_DELIVERY_TYPE = 'SET_SELECTED_COURIERS_DELIVERY_TYPE';
export const CLEAN_COURIERS_DELIVERY_TYPE_STATE = 'CLEAN_COURIERS_DELIVERY_TYPE_STATE';
export const SET_COURIERS_DELIVERY_TYPE_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_DELIVERY_TYPE_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_DELIVERY_TYPE = 'CLEAN_SELECTED_COURIERS_DELIVERY_TYPE';

/* Payment Types */
export const PAYMENT_TYPES = '[PAYMENT_TYPES]';
export const REQUEST_PAYMENT_TYPES_PENDING = `${PAYMENT_TYPES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_PAYMENT_TYPES_SUCCESS = `${PAYMENT_TYPES} ${REQUEST} ${READ}_${SUCCESS}`;
export const CLEAN_PAYMENT_TYPE_STATE = 'CLEAN_PAYMENT_TYPE_STATE';

/* Couriers Payment Types */
export const COURIERS_PAYMENT_TYPES = '[COURIERS_PAYMENT_TYPES]';
export const REQUEST_COURIERS_PAYMENT_TYPES_PENDING = `${COURIERS_PAYMENT_TYPES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_PAYMENT_TYPES_SUCCESS = `${COURIERS_PAYMENT_TYPES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIERS_PAYMENT_TYPE = 'SET_SELECTED_COURIERS_PAYMENT_TYPE';
export const CLEAN_COURIERS_PAYMENT_TYPE_STATE = 'CLEAN_COURIERS_PAYMENT_TYPE_STATE';
export const SET_COURIERS_PAYMENT_TYPE_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_PAYMENT_TYPE_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_PAYMENT_TYPE = 'CLEAN_SELECTED_COURIERS_PAYMENT_TYPE';

/* Transport Types */
export const TRANSPORT_TYPES = '[TRANSPORT_TYPES]';
export const REQUEST_TRANSPORT_TYPES_PENDING = `${TRANSPORT_TYPES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_TRANSPORT_TYPES_SUCCESS = `${TRANSPORT_TYPES} ${REQUEST} ${READ}_${SUCCESS}`;
export const CLEAN_TRANSPORT_TYPE_STATE = 'CLEAN_TRANSPORT_TYPE_STATE';

/* Couriers Transport Types */
export const COURIERS_TRANSPORT_TYPES = '[COURIERS_TRANSPORT_TYPES]';
export const REQUEST_COURIERS_TRANSPORT_TYPES_PENDING = `${COURIERS_TRANSPORT_TYPES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_TRANSPORT_TYPES_SUCCESS = `${COURIERS_TRANSPORT_TYPES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIERS_TRANSPORT_TYPE = 'SET_SELECTED_COURIERS_TRANSPORT_TYPE';
export const CLEAN_COURIERS_TRANSPORT_TYPE_STATE = 'CLEAN_COURIERS_TRANSPORT_TYPE_STATE';
export const CLEAN_COURIERS_TRANSPORT_TYPE = 'CLEAN_COURIERS_TRANSPORT_TYPE';
export const SET_COURIERS_TRANSPORT_TYPE_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_TRANSPORT_TYPE_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_TRANSPORT_TYPE = 'CLEAN_SELECTED_COURIERS_TRANSPORT_TYPE';

/* Couriers Branch Offices */
export const COURIERS_BRANCH_OFFICES = '[COURIERS_BRANCH_OFFICES]';
export const REQUEST_COURIERS_BRANCH_OFFICES_PENDING = `${COURIERS_BRANCH_OFFICES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_BRANCH_OFFICES_SUCCESS = `${COURIERS_BRANCH_OFFICES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIERS_BRANCH_OFFICE = 'SET_SELECTED_COURIERS_BRANCH_OFFICE';
export const SET_COURIERS_BRANCH_OFFICE_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_BRANCH_OFFICE_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_BRANCH_OFFICE = 'CLEAN_SELECTED_COURIERS_BRANCH_OFFICE';
export const CLEAN_COURIERS_BRANCH_OFFICE_STATE = 'CLEAN_COURIERS_BRANCH_OFFICE_STATE';

/* Couriers Insurance Configurations */
export const COURIERS_INSURANCE_CONFIGURATIONS = '[COURIERS_INSURANCE_CONFIGURATIONS]';
export const REQUEST_COURIERS_INSURANCE_CONFIGURATIONS_PENDING = `${COURIERS_INSURANCE_CONFIGURATIONS} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_INSURANCE_CONFIGURATIONS_SUCCESS = `${COURIERS_INSURANCE_CONFIGURATIONS} ${REQUEST} ${READ}_${SUCCESS}`;
export const CLEAN_COURIERS_INSURANCE_CONFIGURATION_STATE =
  'CLEAN_COURIERS_INSURANCE_CONFIGURATION_STATE';
export const SET_SELECTED_COURIERS_INSURANCE_CONFIGURATION =
  'SET_SELECTED_COURIERS_INSURANCE_CONFIGURATION';
export const SET_COURIERS_INSURANCE_CONFIGURATION_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_INSURANCE_CONFIGURATION_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_INSURANCE_CONFIGURATION =
  'CLEAN_SELECTED_COURIERS_INSURANCE_CONFIGURATION';

/* Couriers Service Types */
export const COURIERS_SERVICE_TYPES = '[COURIERS_SERVICE_TYPES]';
export const REQUEST_COURIERS_SERVICE_TYPES_PENDING = `${COURIERS_SERVICE_TYPES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_SERVICE_TYPES_SUCCESS = `${COURIERS_SERVICE_TYPES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIERS_SERVICE_TYPE = 'SET_SELECTED_COURIERS_SERVICE_TYPE';
export const CLEAN_COURIERS_SERVICE_TYPE_STATE = 'CLEAN_COURIERS_SERVICE_TYPE_STATE';
export const SET_COURIERS_SERVICE_TYPE_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_SERVICE_TYPE_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_SERVICE_TYPE = 'CLEAN_SELECTED_COURIERS_SERVICE_TYPE';
export const CLEAN_COURIERS_SERVICE_TYPES = `${CLEAN}_${COURIERS_SERVICE_TYPES}`;

/* Couriers Coverages */
export const COURIERS_COVERAGES = '[COURIERS_COVERAGES]';
export const REQUEST_COURIERS_COVERAGES_PENDING = `${COURIERS_COVERAGES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_COVERAGES_SUCCESS = `${COURIERS_COVERAGES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIERS_COVERAGE = 'SET_SELECTED_COURIERS_COVERAGE';
export const CLEAN_COURIERS_COVERAGE_STATE = 'CLEAN_COURIERS_COVERAGE_STATE';
export const SET_COURIERS_COVERAGE_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_COVERAGE_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_COVERAGE = 'CLEAN_SELECTED_COURIERS_COVERAGE';
export const SET_COURIER_COVERAGES_PAGINATION = 'SET_COURIER_COVERAGES_PAGINATION';

/* Couriers Destinies */
export const COURIERS_DESTINIES = '[COURIERS_DESTINIES]';
export const REQUEST_COURIERS_DESTINIES_PENDING = `${COURIERS_DESTINIES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_DESTINIES_SUCCESS = `${COURIERS_DESTINIES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIERS_DESTINY = 'SET_SELECTED_COURIERS_DESTINY';
export const CLEAN_COURIERS_DESTINY_STATE = 'CLEAN_COURIERS_DESTINY_STATE';
export const SET_COURIERS_DESTINY_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_DESTINY_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_DESTINY = 'CLEAN_SELECTED_COURIERS_DESTINY';

/* Couriers Origins */
export const COURIERS_ORIGINS = '[COURIERS_ORIGINS]';
export const REQUEST_COURIERS_ORIGINS_PENDING = `${COURIERS_ORIGINS} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIERS_ORIGINS_SUCCESS = `${COURIERS_ORIGINS} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIERS_ORIGIN = 'SET_SELECTED_COURIERS_ORIGIN';
export const CLEAN_COURIERS_ORIGIN_STATE = 'CLEAN_COURIERS_ORIGIN_STATE';
export const SET_COURIERS_ORIGIN_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIERS_ORIGIN_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIERS_ORIGIN = 'CLEAN_SELECTED_COURIERS_ORIGIN';

/* Management Steps */
export const MANAGEMENT_STEPS = '[MANAGEMENT_STEPS]';
export const READ_SUB_STATUS_AVAILABLES = `${MANAGEMENT_STEPS} READ_SUB_STATUS_AVAILABLES`;
export const REMOVE_SUB_STATUS = `${MANAGEMENT_STEPS} REMOVE_SUB_STATUS`;
export const ADD_SUB_STATUSES = `${MANAGEMENT_STEPS} ADD_SUB_STATUSES`;
export const SET_ATTRIBUTE_FORM = `${MANAGEMENT_STEPS} SET_ATTRIBUTE_FORM`;

/* Price Configurations */
export const PRICE_CONFIGURATIONS = '[PRICE_CONFIGURATIONS]';
export const REQUEST_PRICE_CONFIGURATIONS_PENDING = `${PRICE_CONFIGURATIONS} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_PRICE_CONFIGURATIONS_SUCCESS = `${PRICE_CONFIGURATIONS} ${REQUEST} ${READ}_${SUCCESS}`;
export const CLEAN_PRICE_CONFIGURATION_STATE = 'CLEAN_PRICE_CONFIGURATION_STATE';
export const PRICE_CONFIGURATION_LOADING = 'PRICE_CONFIGURATION_LOADING';
export const PRICE_CONFIGURATION_NOT_LOADING = 'PRICE_CONFIGURATION_NOT_LOADING';
export const SET_PRICE_CONFIGURATION_PAGINATION = 'SET_PRICE_CONFIGURATION_PAGINATION';

/* Couriers Sub Statuses */
export const COURIER_SUB_STATUS = '[COURIER_SUB_STATUS]';
export const COURIER_SUB_STATUSES = '[COURIER_SUB_STATUSES]';
export const REQUEST_COURIER_SUB_STATUSES_PENDING = `${COURIER_SUB_STATUSES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_COURIER_SUB_STATUSES_SUCCESS = `${COURIER_SUB_STATUSES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_COURIER_SUB_STATUS = 'SET_SELECTED_COURIER_SUB_STATUS';
export const CLEAN_COURIER_SUB_STATUS_STATE = 'CLEAN_COURIER_SUB_STATUS_STATE';
export const SET_COURIER_SUB_STATUS_RIGHT_DRAWER_VISIBILITY =
  'SET_COURIER_SUB_STATUS_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_COURIER_SUB_STATUS = 'CLEAN_SELECTED_COURIER_SUB_STATUS';

/* Sub Statuses */
export const SUB_STATUS = '[SUB_STATUS]';
export const SUB_STATUSES = '[SUB_STATUSES]';
export const REQUEST_SUB_STATUSES_PENDING = `${SUB_STATUSES} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_SUB_STATUSES_SUCCESS = `${SUB_STATUSES} ${REQUEST} ${READ}_${SUCCESS}`;
export const SET_SELECTED_SUB_STATUS = 'SET_SELECTED_SUB_STATUS';
export const CLEAN_SUB_STATUS_STATE = 'CLEAN_SUB_STATUS_STATE';
export const SET_SUB_STATUS_RIGHT_DRAWER_VISIBILITY = 'SET_SUB_STATUS_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_SUB_STATUS = 'CLEAN_SELECTED_SUB_STATUS';

/* Courier Operational Information */
export const COURIER_OPERATIONAL_INFORMATIONS = '[COURIER_OPERATIONAL_INFORMATIONS]';
export const SET_SELECTED_OP_INFORMATION = `${COURIER_OPERATIONAL_INFORMATIONS} SET_SELECTED_OP_INFORMATION`;
export const SET_OP_INFORMATION_RIGHT_DRAWER_VISIBILITY = `${COURIER_OPERATIONAL_INFORMATIONS} SET_OP_INFORMATION_RIGHT_DRAWER_VISIBILITY`;
export const CLEAN_OP_INFORMATION_STATE = `${COURIER_OPERATIONAL_INFORMATIONS} CLEAN_OP_INFORMATION_STATE`;
export const CLEAN_SELECTED_OP_INFORMATION = `${COURIER_OPERATIONAL_INFORMATIONS} CLEAN_SELECTED_OP_INFORMATION`;

/* Shipment Discounts */
export const SHIPMENT_DISCOUNTS = '[SHIPMENT_DISCOUNTS]';
export const REQUEST_SHIPMENT_DISCOUNTS_PENDING = `${SHIPMENT_DISCOUNTS} ${REQUEST} ${READ}_${PENDING}`;
export const REQUEST_SHIPMENT_DISCOUNTS_SUCCESS = `${SHIPMENT_DISCOUNTS} ${REQUEST} ${READ}_${SUCCESS}`;
export const CLEAN_SHIPMENT_DISCOUNT_STATE = 'CLEAN_SHIPMENT_DISCOUNT_STATE';
export const ACTIVATE = '[ACTIVATE]';
export const SET_SHIPMENT_DISCOUNT_RULES = 'SET_SHIPMENT_DISCOUNT_RULES';
export const SET_UPDATE_RULES = 'SET_UPDATE_RULES';
export const DELETE_RULE = 'DELETE_RULE';
export const CLEAR_RULES = 'CLEAR_RULES';
export const FIX_KINDS = 'FIX_KINDS';
export const BUILD_SHIPMENTS_DISCOUNT_RULES = 'BUILD_SHIPMENTS_DISCOUNT_RULES';
export const SET_TEMP_RULE_VALUE = 'SET_TEMP_RULE_VALUE';

/* Monthly Charges */
export const MONTHLY_CHARGES = '[MONTHLY_CHARGES]';
export const CLEAN_MONTHLY_CHARGES_STATE = 'CLEAN_MONTHLY_CHARGES_STATE';
export const SET_MONTHLY_CHARGES_RULES = 'SET_MONTHLY_CHARGES_RULES';

/* Holidays */
export const HOLIDAYS = '[HOLIDAYS]';
export const CLEAN_HOLIDAYS_STATE = 'CLEAN_HOLIDAYS_STATE';
export const ACTIVATE_HOLIDAYS = '[ACTIVATE]';
export const SET_SELECTED_HOLIDAY = 'SET_SELECTED_HOLIDAY';
export const CLEAN_HOLIDAY_STATE = 'CLEAN_HOLIDAY_STATE';
export const SET_HOLIDAY_RIGHT_DRAWER_VISIBILITY = 'SET_HOLIDAY_RIGHT_DRAWER_VISIBILITY';
export const CLEAN_SELECTED_HOLIDAY = 'CLEAN_SELECTED_HOLIDAY';

/* Regions */
export const REGIONS = 'REGIONS';

/* Courier Credentials */
export const COURIER_CREDENTIALS = 'COURIER_CREDENTIALS';
export const COURIER_CREDENTIAL = 'COURIER_CREDENTIAL';
export const CLEAN_COURIER_CREDENTIAL = `${CLEAN} ${COURIER_CREDENTIAL}`;
export const CREDENTIAL_KEYS = 'CREDENTIAL_KEYS';
export const COURIER_CREDENTIAL_KEYS = `$COURIER_${CREDENTIAL_KEYS}`;
export const CLEAN_COURIER_CREDENTIAL_KEYS = `${CLEAN} ${COURIER_CREDENTIAL_KEYS}`;
export const COURIER_CREDENTIAL_KEY = 'COURIER_CREDENTIAL_KEY';
export const ADD_COURIER_CREDENTIAL_KEY = `${ADD}_${COURIER_CREDENTIAL_KEY}`;
export const DELETE_COURIER_CREDENTIAL_KEY = `${DELETE}_${COURIER_CREDENTIAL_KEY}`;
export const SET_WANT_ADD_BASE_KEY = 'SET_WANT_ADD_BASE_KEY';
export const SET_SHOW_COURIER_CREDENTIAL_KEYS = `${SET}_SHOW_${COURIER_CREDENTIAL_KEYS}`;
export const SET_COURIER_SERVICE_TYPE_ID = 'SET_COURIER_SERVICE_TYPE_ID';
export const SET_COURIER_CREDENTIAL_KEY_ID = 'SET_COURIER_CREDENTIAL_KEY_ID';
export const COURIER_CREDENTIAL_RULES = 'COURIER_CREDENTIAL_RULES';
export const CLEAN_COURIER_CREDENTIAL_RULES = `${CLEAN} ${COURIER_CREDENTIAL_RULES}`;
export const COURIER_CREDENTIAL_RULE = 'COURIER_CREDENTIAL_RULE';
export const ADD_COURIER_CREDENTIAL_RULE = `${ADD}_${COURIER_CREDENTIAL_RULE}`;
export const DELETE_COURIER_CREDENTIAL_RULE = `${DELETE}_${COURIER_CREDENTIAL_RULE}`;
export const HIDDE_COURIER_CREDENTIAL_TYPE = 'HIDDE_COURIER_CREDENTIAL_TYPE';

/* Async Processes */
export const ASYNC_PROCESSES = 'ASYNC_PROCESSES';
export const SET_ASYNC_PROCESSES_PAGINATION = 'SET_ASYNC_PROCESSES_PAGINATION';
export const REDO = 'REDO';
export const ASYNC_PROCESS_LOADING = 'ASYNC_PROCESS_LOADING';
export const ASYNC_PROCESS_NOT_LOADING = 'ASYNC_PROCESS_NOT_LOADING';
