export default {
  shipments: {
    shipmentForm: {
      kind: 0,
      platform: 0,
      reference: '',
      items: 1,
      company_id: 0,
      origin: {
        street: '',
        number: '',
        complement: '',
        commune_id: 0,
        full_name: '',
        email: '',
        phone: '',
        store: false,
        origin_id: null,
        name: ''
      },
      prices: {
        total: 0,
        price: 0,
        cost: 0,
        insurance: 0,
        tax: 0,
        overcharge: 0
      },
      courier: {
        id: '',
        client: '',
        entity: '',
        selected: false,
        algorithm: '1',
        algorithm_days: '2',
        payable: false
      },
      destiny: {
        street: '',
        number: '',
        complement: '',
        commune_id: 0,
        commune_name: '',
        full_name: '',
        email: '',
        phone: '',
        store: false,
        destiny_id: '0',
        delivery_id: '1',
        courier_branch_office_id: -1,
        courier_id: 0,
        fulfillment_delivery: 0,
        name: '',
        kind: 'home_delivery'
      },
      sizes: {
        width: 10,
        height: 10,
        length: 10,
        weight: 1,
        volumetric_weight: 0.25,
        store: false,
        packing_id: '0',
        name: '',
        touch: false
      },
      insurance: {
        ticket_amount: null,
        ticket_number: '',
        store: false,
        name: '',
        company_id: '',
        active: true,
        detail: ''
      },
      products: []
    },
    page: 'new',
    stepPosition: 0,
    selectedShipments: [],
    pdfModalVisibility: false,
    shipments: {
      shipments: [
        {
          id: 2162574,
          reference: 'regalosept1',
          branch_office_id: 1,
          items_count: 1,
          packing: 'Sin empaque',
          status: 'delivered',
          tracking_number: 't-shipob-206',
          courier_status: 'Entregado',
          destiny: 'Domicilio',
          courier_for_client: 'shippify',
          created_at: '2020-08-27T10:28:29.809-04:00',
          updated_at: '2020-08-27T14:35:35.872-04:00',
          is_returned: true,
          total_is_payable: 0,
          email: '',
          cellphone: '56986901500',
          length: 10,
          width: 10,
          height: 10,
          weight: 1,
          is_payable: false,
          payment_date: null,
          shipping_price: 0,
          approx_size: 'Pequeño (10x10x10cm)',
          volume_price: null,
          shipping_type: 'Normal',
          total_price: 0,
          shipit_code: 'Shipit / regalosept',
          estimated_delivery: '',
          courier_url: 'https://api.shippify.co/track/t-shipob-206',
          url_pack: '',
          pack_pdf: '',
          courier_status_updated_at: '2020-08-27 14:35:35 -0400',
          shipit_status_updated_at: '2020-08-27T14:35:35.871-04:00',
          purchase: {
            amount: 50000,
            max_insurance: 0,
            ticket_number: '',
            insurance_price: 0
          },
          operation_date: '2020-08-27',
          inventory_activity: null,
          label_printed: false,
          sub_status: 'delivered',
          courier_branch_office_id: null,
          old_ticket_url_courier: 'https://api.shippify.co/track/t-shipob-206',
          ticket_shipit_url:
            'https://printer-labels.s3.us-west-2.amazonaws.com/shipit/2020/8/27/2162574_shipitlabel.pdf',
          ticket_url: '',
          ticket_shipit_pdf_url: '',
          shipit_tracking_link: 'https://seguimiento.shipit.cl/statuses?number=t-shipob-206',
          address: {
            id: 2240354,
            commune_id: 316,
            complement: '',
            number: '7913',
            street: 'camino del cedro',
            coords: {
              latitude: 0,
              longitude: 0
            },
            created_at: '2020-08-27T10:28:29.838-04:00',
            updated_at: '2020-08-27T10:28:29.838-04:00',
            package_id: 2162574,
            full: 'camino del cedro 7913, Penalolen, Región Metropolitana',
            commune_name: 'PENALOLEN'
          },
          overcharge: 0,
          total: 0,
          editable: false,
          archivable: false,
          returnable: false,
          schedulable: false,
          integration_reference: null,
          origin: {
            street: 'avenida apoquindo ',
            number: '8053',
            complement: 'depto 111',
            commune_id: 308,
            full: 'avenida apoquindo  8053, Las Condes, Región Metropolitana, Chile',
            full_name: 'Staff Shipit',
            email: '',
            phone: '',
            store: false,
            name: 'default'
          },
          check_in: false,
          check_out: false,
          notifications: [],
          whatsapps: [],
          full_name: 'Felipe Muñoz',
          tickets: {
            quantity: 0,
            last_ticket: null
          },
          order: null,
          insurance: null,
          last_pickup: null,
          estimated_pickup_time: null
        },
        {
          id: 2082903,
          reference: 'FeChi14',
          branch_office_id: 1,
          items_count: 1,
          packing: 'Sin Empaque',
          status: 'delivered',
          tracking_number: 't-shipob-158',
          courier_status: 'Entregado',
          destiny: 'domicilio',
          courier_for_client: 'shippify',
          created_at: '2020-08-14T10:40:56.117-04:00',
          updated_at: '2020-08-14T15:40:43.732-04:00',
          is_returned: false,
          total_is_payable: 0,
          email: 'felipe.chibey@shipit.cl',
          cellphone: '',
          length: 10,
          width: 10,
          height: 10,
          weight: 1,
          is_payable: false,
          payment_date: null,
          shipping_price: 5224,
          approx_size: 'Pequeño (10x10x10cm)',
          volume_price: 1,
          shipping_type: 'Normal',
          total_price: 5224,
          shipit_code: 'Shipit / FeChi14',
          estimated_delivery: '',
          courier_url: 'https://api.shippify.co/track/t-shipob-158',
          url_pack: '',
          pack_pdf: '',
          courier_status_updated_at: '2020-08-14 15:40:43 -0400',
          shipit_status_updated_at: '2020-08-14T15:40:43.732-04:00',
          purchase: {
            amount: 0,
            detail: '',
            max_insurance: 0,
            ticket_number: '',
            extra_insurance: false,
            insurance_price: 0
          },
          operation_date: '2020-08-14',
          inventory_activity: null,
          label_printed: false,
          sub_status: 'delivered',
          courier_branch_office_id: null,
          old_ticket_url_courier: 'https://api.shippify.co/track/t-shipob-158',
          ticket_shipit_url:
            'https://printer-labels.s3.us-west-2.amazonaws.com/shipit/2020/8/14/2082903_shipitlabel.pdf',
          ticket_url: '',
          ticket_shipit_pdf_url: '',
          shipit_tracking_link: 'https://seguimiento.shipit.cl/statuses?number=t-shipob-158',
          address: {
            id: 2158696,
            commune_id: 314,
            complement: 'Depto 31 v',
            number: '587',
            street: 'Ortuzar',
            coords: {
              latitude: 0,
              longitude: 0
            },
            created_at: '2020-08-14T10:40:56.161-04:00',
            updated_at: '2020-08-14T10:40:56.161-04:00',
            package_id: 2082903,
            full: 'Ortuzar 587, Nunoa, Región Metropolitana',
            commune_name: 'NUNOA'
          },
          overcharge: 0,
          total: 5224,
          editable: false,
          archivable: false,
          returnable: false,
          schedulable: false,
          integration_reference: null,
          origin: {
            street: 'avenida apoquindo ',
            number: '8053',
            complement: 'depto 111',
            commune_id: 308,
            full: 'avenida apoquindo  8053, Las Condes, Región Metropolitana, Chile',
            full_name: 'Staff Shipit',
            email: '',
            phone: '',
            store: false,
            name: 'default'
          },
          check_in: false,
          check_out: false,
          notifications: [
            {
              state: 'delivered',
              sent: true
            }
          ],
          whatsapps: [],
          full_name: 'Felipe Chibey',
          tickets: {
            quantity: 0,
            last_ticket: null
          },
          order: null,
          insurance: {
            id: 718675,
            ticket_amount: null,
            ticket_number: '',
            price: 0,
            detail: '',
            company_id: null,
            archive: false,
            created_at: '2020-08-14T10:40:56.227-04:00',
            updated_at: '2020-08-14T10:40:56.345-04:00',
            extra: false,
            package_id: 2082903,
            active: true
          },
          last_pickup: null,
          estimated_pickup_time: null
        }
      ],
      total: 2
    },
    sizes: {
      total: 2,
      delivered: 0,
      in_preparation: 0,
      created: 2,
      in_route: 0,
      failed: 0,
      returned: 0
    },
    shipment: {},
    formShipment: {
      courier_for_client: ''
    },
    rightDrawerVisibility: false,
    downloadLinkLoading: false,
    loading: false,
    selectedCourier: {},
    prices: {},
    link: '',
    statuses: [],
    bottomDrawerVisible: false
  }
};
