export default [
  {
    id: 2082903,
    reference: 'FeChi14',
    branch_office_id: 1,
    items_count: 1,
    packing: 'Sin Empaque',
    status: 'delivered',
    tracking_number: 't-shipob-158',
    courier_status: 'Entregado',
    destiny: 'domicilio',
    courier_for_client: 'shippify',
    created_at: '2020-08-14T10:40:56.117-04:00',
    updated_at: '2020-08-14T15:40:43.732-04:00',
    is_returned: false,
    total_is_payable: 0,
    email: 'felipe.chibey@shipit.cl',
    cellphone: '',
    length: 10,
    width: 10,
    height: 10,
    weight: 1,
    is_payable: false,
    payment_date: null,
    shipping_price: 5224,
    approx_size: 'Pequeño (10x10x10cm)',
    volume_price: 1,
    shipping_type: 'Normal',
    total_price: 5224,
    shipit_code: 'Shipit / FeChi14',
    estimated_delivery: '',
    courier_url: 'https://api.shippify.co/track/t-shipob-158',
    url_pack: '',
    pack_pdf: '',
    courier_status_updated_at: '2020-08-14 15:40:43 -0400',
    shipit_status_updated_at: '2020-08-14T15:40:43.732-04:00',
    purchase: {
      amount: 0,
      detail: '',
      max_insurance: 0,
      ticket_number: '',
      extra_insurance: false,
      insurance_price: 0
    },
    operation_date: '2020-08-14',
    inventory_activity: null,
    label_printed: false,
    sub_status: 'delivered',
    courier_branch_office_id: null,
    old_ticket_url_courier: 'https://api.shippify.co/track/t-shipob-158',
    ticket_shipit_url:
      'https://printer-labels.s3.us-west-2.amazonaws.com/shipit/2020/8/14/2082903_shipitlabel.pdf',
    ticket_url: '',
    ticket_shipit_pdf_url: '',
    shipit_tracking_link: 'https://seguimiento.shipit.cl/statuses?number=t-shipob-158',
    address: {
      id: 2158696,
      commune_id: 314,
      complement: 'Depto 31 v',
      number: '587',
      street: 'Ortuzar',
      coords: {
        latitude: 0,
        longitude: 0
      },
      created_at: '2020-08-14T10:40:56.161-04:00',
      updated_at: '2020-08-14T10:40:56.161-04:00',
      package_id: 2082903,
      full: 'Ortuzar 587, Nunoa, Región Metropolitana',
      commune_name: 'NUNOA'
    },
    overcharge: 0,
    total: 5224,
    editable: false,
    archivable: false,
    returnable: false,
    schedulable: false,
    integration_reference: null,
    origin: {
      street: 'avenida apoquindo ',
      number: '8053',
      complement: 'depto 111',
      commune_id: 308,
      full: 'avenida apoquindo  8053, Las Condes, Región Metropolitana, Chile',
      full_name: 'Staff Shipit',
      email: '',
      phone: '',
      store: false,
      name: 'default'
    },
    check_in: false,
    check_out: false,
    notifications: [
      {
        state: 'delivered',
        sent: true
      }
    ],
    whatsapps: [],
    full_name: 'Felipe Chibey',
    tickets: {
      quantity: 0,
      last_ticket: null
    },
    order: null,
    insurance: {
      id: 718675,
      ticket_amount: null,
      ticket_number: '',
      price: 0,
      detail: '',
      company_id: null,
      archive: false,
      created_at: '2020-08-14T10:40:56.227-04:00',
      updated_at: '2020-08-14T10:40:56.345-04:00',
      extra: false,
      package_id: 2082903,
      active: true
    },
    last_pickup: null,
    estimated_pickup_time: null
  }
];
