export default {
  data: [
    {
      id: 2247319,
      full_name: 'Zamiz Tobar Staging',
      length: 10.0,
      width: 10.0,
      height: 10.0,
      weight: 1.0,
      volume_price: 1.0,
      reference: 'tst-sucur2',
      is_payable: false,
      is_paid_shipit: false,
      is_returned: false,
      items_count: 1,
      tracking_number: 'SHI-0NKP4U',
      shipping_price: 3900.0,
      created_at: '2020-09-07T11:53:27.062-03:00',
      material_extra: 0,
      discount_amount: 0.0,
      payment_date: null,
      courier: 'motopartner',
      overcharge: 0.0,
      total: 3900.0,
      address_street: 'Apoquindo',
      address_number: '4499',
      address_commune_name: 'NUNOA',
      insurance_total_price: 0.0,
      insurance_extra: false,
      insurance_active: true
    },
    {
      id: 2246573,
      full_name: 'Zamiz Tobar',
      length: 10.0,
      width: 10.0,
      height: 10.0,
      weight: 1.0,
      volume_price: 1.0,
      reference: 'tst-sucur1',
      is_payable: false,
      is_paid_shipit: false,
      is_returned: false,
      items_count: 1,
      tracking_number: 'SHI-DPEOO9',
      shipping_price: 3900.0,
      created_at: '2020-09-07T10:31:03.836-03:00',
      material_extra: 0,
      discount_amount: 0.0,
      payment_date: null,
      courier: 'motopartner',
      overcharge: 0.0,
      total: 3900.0,
      address_street: 'Apoquindo',
      address_number: '4499',
      address_commune_name: 'NUNOA',
      insurance_total_price: 0.0,
      insurance_extra: false,
      insurance_active: true
    },
    {
      id: 2246446,
      full_name: 'Zamiz Tobar',
      length: 10.0,
      width: 10.0,
      height: 10.0,
      weight: 1.0,
      volume_price: 1.0,
      reference: 'tst-sucurs',
      is_payable: false,
      is_paid_shipit: false,
      is_returned: false,
      items_count: 1,
      tracking_number: 'SHI-26LZB5',
      shipping_price: 3900.0,
      created_at: '2020-09-07T10:22:25.089-03:00',
      material_extra: 0,
      discount_amount: 0.0,
      payment_date: null,
      courier: 'motopartner',
      overcharge: 0.0,
      total: 3900.0,
      address_street: 'Apoquindo',
      address_number: '4499',
      address_commune_name: 'NUNOA',
      insurance_total_price: 0.0,
      insurance_extra: false,
      insurance_active: true
    },
    {
      id: 2246147,
      full_name: 'Fabiola Manríquez',
      length: 10.0,
      width: 10.0,
      height: 10.0,
      weight: 1.0,
      volume_price: 1.0,
      reference: '#S10Tst1058',
      is_payable: false,
      is_paid_shipit: false,
      is_returned: false,
      items_count: 1,
      tracking_number: '935869445',
      shipping_price: 4510.0,
      created_at: '2020-09-07T10:03:02.475-03:00',
      material_extra: 0,
      discount_amount: 0.0,
      payment_date: null,
      courier: 'starken',
      overcharge: 0.0,
      total: 4510.0,
      address_street: 'Calle Portillo Alto',
      address_number: '3150',
      address_commune_name: 'QUILPUE',
      insurance_total_price: 0.0,
      insurance_extra: false,
      insurance_active: true
    },
    {
      id: 2230763,
      full_name: 'hior',
      length: 10.0,
      width: 10.0,
      height: 10.0,
      weight: 1.0,
      volume_price: 1.0,
      reference: 'hior',
      is_payable: false,
      is_paid_shipit: false,
      is_returned: false,
      items_count: 1,
      tracking_number: 'SHI-88ZBHN',
      shipping_price: 3900.0,
      created_at: '2020-09-04T07:19:34.525-04:00',
      material_extra: 0,
      discount_amount: 0.0,
      payment_date: null,
      courier: 'motopartner',
      overcharge: 0.0,
      total: 3900.0,
      address_street: 'asssssss',
      address_number: '33333333',
      address_commune_name: 'LAS CONDES',
      insurance_total_price: 0.0,
      insurance_extra: false,
      insurance_active: true
    },
    {
      id: 2219496,
      full_name: 'hirocarpo avendaños',
      length: 10.0,
      width: 10.0,
      height: 10.0,
      weight: 1.0,
      volume_price: 1.0,
      reference: '#40',
      is_payable: false,
      is_paid_shipit: false,
      is_returned: false,
      items_count: 1,
      tracking_number: '2219496691540',
      shipping_price: 3913.0,
      created_at: '2020-09-03T08:04:00.876-04:00',
      material_extra: 0,
      discount_amount: 0.0,
      payment_date: null,
      courier: 'chileparcels',
      overcharge: 0.0,
      total: 3913.0,
      address_street: '200 primaveras ',
      address_number: '2000',
      address_commune_name: 'PROVIDENCIA',
      insurance_total_price: 0.0,
      insurance_extra: false,
      insurance_active: true
    },
    {
      id: 2189426,
      full_name: 'Jose Tomas',
      length: 10.0,
      width: 10.0,
      height: 10.0,
      weight: 1.0,
      volume_price: 1.0,
      reference: 'tst-edicion',
      is_payable: false,
      is_paid_shipit: false,
      is_returned: false,
      items_count: 1,
      tracking_number: '6707562702',
      shipping_price: 9008.0,
      created_at: '2020-09-01T04:08:28.322-04:00',
      material_extra: 0,
      discount_amount: 0.0,
      payment_date: null,
      courier: 'bluexpress',
      overcharge: 0.0,
      total: 9008.0,
      address_street: 'av po editado',
      address_number: '32',
      address_commune_name: 'MARCHIGUE',
      insurance_total_price: 0.0,
      insurance_extra: false,
      insurance_active: true
    }
  ],
  total: 7
};
